version: "3.8"

services:
  db:
    container_name: db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: PyEditorial_prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: great123
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn PyEditorial.wsgi:application --bind 0.0.0.0:8000
    environment:
      DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 [::1]
      DATABASE: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: PyEditorial_prod
      POSTGRES_PASSWORD: great123
      DEBUG: 0
    expose:
      - 8000
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

volumes:
  postgres_data_prod:
